### ISSUE TITLE
[Tangram R&D] Alpha channel with blend

### ISSUE THREAD

**Issue by donflopez** [CartoDB/tangram-carto#12]
After the opacity implementation (#9), we're having a problem with the colour calculation, it is calculated avoiding the colour behind himself and using the background colour of the canvas (0, 0, 0, 0) -> white. So, were having this experience:

- It should look like this:

<img width="148" alt="screen shot 2016-11-23 at 10 18 52" src="https://cloud.githubusercontent.com/assets/463462/20556213/4a8854b0-b166-11e6-8a95-6cb177135f9b.png">

- Colour avoiding:

<img width="166" alt="screen shot 2016-11-23 at 10 16 37" src="https://cloud.githubusercontent.com/assets/463462/20556166/0f2ae432-b166-11e6-9ba9-421083d86afb.png">

It seems to be a problem with the blend configuration, Tangram uses `opaque` by default and it should be `overlay`, but changing it is not enough.

I'm still working on it, I'll create a new branch with a working example for collaborations.

This issue is part of the #11 metaissue

/cc @javisantana

**Comment by donflopez** [comment]
With [this changes](https://github.com/tangrams/tangram/pull/455) to tangram it is solved.

**Comment by donflopez** [comment]
Finally, It was a bug in tangram, fixed now, and the existence of a buffer on our tile api not supported by Tangram.

**Comment by donflopez** [comment]
[This](https://github.com/CartoDB/Windshaft/issues/522) fix this issue.

**Comment by alonsogarciapablo** [comment]
Closing this for now.
