### ISSUE TITLE
[Tangram R&D] Polygons draw are buggy

### ISSUE THREAD

**Issue by donflopez** [CartoDB/tangram-carto#13]
Drawing polygons from carto MVT source, the draw of the polygons are drawn wrongly.

This is the correct form:

<img width="234" alt="screen shot 2016-11-23 at 10 53 55" src="https://cloud.githubusercontent.com/assets/463462/20557296/3e788622-b16b-11e6-9ed9-d7e310d8b951.png">

And here is the tangram form:

<img width="222" alt="screen shot 2016-11-23 at 10 53 38" src="https://cloud.githubusercontent.com/assets/463462/20557330/55720312-b16b-11e6-9b8f-10f87aec7ba5.png">

It seems to be related with a problem with the aggregations made by tangram to reduce the points collisions.

This issue is part of the #11 metaissue

**Comment by jgoizueta** [comment]
@donflopez could you provide some sample data and STR instructions for this case?

If this request requires any significant amount of work on your part, please feel free to ignore it, I'd just like to take a quick look at the problem, but not to be a burden.

**Comment by donflopez** [comment]
Hi @jgoizueta, it seems that is fixed now in the master branch of Tangram :)

Thanks! I'm waiting to confirm it in production to close it.

**Comment by jgoizueta** [comment]
😄

**Comment by donflopez** [comment]
It is fixed!! Tried in production.

cc/ @rochoa & @javisantana

**Comment by javisantana** [comment]
what was it ?
