### ISSUE TITLE
demo attribution  ... 

### ISSUE THREAD

**Issue by ImreSamu** [CartoDB/tangram-carto#22]
(idea) It is possible to use  cartodb -  [default_layers.js](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/default_layers.js)  for  [this demo](https://cartodb.github.io/tangram-carto/)  attributions ? ( https://github.com/CartoDB/cartodb/wiki/How-to-configure-basemaps-in-CartoDB )

As I see - Now - the OpenStreetMap attribution is missing, and it can be a problem, if somebody forks this repo - and don't read the https://github.com/CartoDB/cartodb/wiki/How-to-configure-basemaps-in-CartoDB guideline.

![image](https://cloud.githubusercontent.com/assets/2217320/21802043/7da532a8-d724-11e6-9e81-8f65d96026e5.png)

**Comment by donflopez** [comment]
Yeah, sorry!

I'll put the correct attributions, thanks!!

**Comment by ImreSamu** [comment]
No problem ! 

 :earth_africa: :sunny:   :earth_americas: :sunny:   :earth_asia:  :sunny:  

https://pinterest.com/search/pins/?q=Cute%20maps

**Comment by donflopez** [comment]
Hi @ImreSamu! I've updated the attributions and the demo page with the latest improvements :)

Thank you again!
