### ISSUE TITLE
[Tangram R&D] Basic text support

### ISSUE THREAD

**Issue by donflopez** [CartoDB/tangram-carto#26]
Now we support this new text references

- `text-name`
- `text-fill`
- `text-opacity`
- `text-size`

**Comment by donflopez** [comment]
## Acceptance Criteria:

**Prerequisites:**
- clone this repo master branch
- npm i
- npm run start

**Play with tangram-carto!**
- go to the printer URL
- click on the go button
- go to Paris
- click on the layer name to open the CCSS editor
- add a text-name property with a string or a property of the dataset
- see the result
- play this the above features!

You should see something like this
![screen shot 2017-02-08 at 11 00 17](https://cloud.githubusercontent.com/assets/463462/22732318/05926c46-edee-11e6-9df7-b1fc0ff5ae21.png)

Come on!

**Comment by ethervoid** [comment]
The average case works perfectly but I have a question about error handling.

For example if I add `text-fill: fff` without `#` I get the following error trace in the chrome console:

```
Tangram v0.11.8 [error]: tile load error for CartoDB/9/256/176/9: TypeError: Cannot read property '3' of undefined
    at Object.Utils.toCSSColor (http://192.168.20.2:8000/node_modules/tangram/dist/tangram.debug.js:42150:14)
    at Object.compute (http://192.168.20.2:8000/node_modules/tangram/dist/tangram.debug.js:39443:56)
    at Object.parseTextFeature (http://192.168.20.2:8000/node_modules/tangram/dist/tangram.debug.js:39141:53)
    at Object.addFeature (http://192.168.20.2:8000/node_modules/tangram/dist/tangram.debug.js:35603:14)
    at Function.buildGeometry (http://192.168.20.2:8000/node_modules/tangram/dist/tangram.debug.js:40068:35)
    at http://192.168.20.2:8000/node_modules/tangram/dist/tangram.debug.js:32602:40
log @ log.js:37
(anonymous) @ worker_broker.js:220
WorkerBrokerMainThreadHandler @ worker_broker.js:206
```

It's this ok? We shouldn't give a more friendly approach?

**Comment by donflopez** [comment]
Good point @ethervoid, this kind of errors should be thrown by carto, and that's gonna be when [this PR](https://github.com/CartoDB/carto/pull/27) is merged and used properly in tangram-carto :)

**Comment by ethervoid** [comment]
Oki then 🇬🇲
