### ISSUE TITLE
Private / password protected maps do not load

### ISSUE THREAD

**Issue by javitonino** [CartoDB/tangram-carto#28]
When trying to open a password protected map with the vector flag set to true, the tiler responds with `403` for all `.mvt`. It seems the requests are being made without auth token.

STR:
1. Create a map
2. Make it password protected
3. Open the embed with `?vector=true`

The request should be sent with the specified auth tokens.

We should test everything that depends on auth tokens:
- Private embeds
- Password protected embeds
- Maps shared within organizations: at organization, groups and user level.

In any case, just sending all the auth tokens present in the HTML should be enough to get it to work.

cc @donflopez

**Comment by donflopez** [comment]
Thank you, @javitonino!

[This](https://mapzen.com/documentation/tangram/sources/#access-tokens) could be the solution, I'll take a look :)

**Comment by ethervoid** [comment]
There is an ongoing conversation about this but I don't feel like I could contribute more so unassigning myself...

**Comment by rafatower** [comment]
Fixed

**Comment by rafatower** [comment]
Deployed and fixed, this time for real. Cheers!
