### ISSUE TITLE
[Tangram R&D] Layers order doesn't match

### ISSUE THREAD

**Issue by donflopez** [CartoDB/tangram-carto#30]
The layers order doesn't match with the raster version.

[Raster](https://team.carto.com/u/saleiva/builder/8123f4ff-52eb-4b9e-81dc-5ecf69469f9f/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B40.49918094806632%2C-74.06106948852539%5D%2C%22sw%22%3A%5B40.66709790906187%2C-73.89627456665039%5D%7D%2C%22widgets%22%3A%7B%2239ee0c57-74b9-433e-9daf-4d75605c97a9%22%3A%7B%22normalized%22%3Atrue%7D%2C%229bc213fd-c89b-43eb-bbb9-1e3a35c11d3b%22%3A%7B%22normalized%22%3Atrue%7D%2C%22135e059f-30e6-491f-affe-873050e2a5aa%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D) vs [Vector](https://team.carto.com/u/saleiva/builder/8123f4ff-52eb-4b9e-81dc-5ecf69469f9f/embed?vector=true&state=%7B%22map%22%3A%7B%22ne%22%3A%5B40.49918094806632%2C-74.06106948852539%5D%2C%22sw%22%3A%5B40.66709790906187%2C-73.89627456665039%5D%7D%2C%22widgets%22%3A%7B%2239ee0c57-74b9-433e-9daf-4d75605c97a9%22%3A%7B%22normalized%22%3Atrue%7D%2C%229bc213fd-c89b-43eb-bbb9-1e3a35c11d3b%22%3A%7B%22normalized%22%3Atrue%7D%2C%22135e059f-30e6-491f-affe-873050e2a5aa%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D)

The cause is that with the overlay blend type the points goes behind the polygons, so the order have to be setted in the style layer.

cc/ @saleiva

**Comment by dgaubert** [comment]
CR: 🇨🇭

**Comment by donflopez** [comment]
## Acceptance Criteria:

### Prerequisites
- git clone && git checkout PR branch
- cd project
- npm i
- npm run start
- Set this URL in the input -> `https://saleiva.carto.com/builder/8123f4ff-52eb-4b9e-81dc-5ecf69469f9f/embed`
- Press go

### Criteria:
Look at the [raster map](https://team.carto.com/u/saleiva/builder/8123f4ff-52eb-4b9e-81dc-5ecf69469f9f/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B40.49918094806632%2C-74.06106948852539%5D%2C%22sw%22%3A%5B40.66709790906187%2C-73.89627456665039%5D%7D%2C%22widgets%22%3A%7B%2239ee0c57-74b9-433e-9daf-4d75605c97a9%22%3A%7B%22normalized%22%3Atrue%7D%2C%229bc213fd-c89b-43eb-bbb9-1e3a35c11d3b%22%3A%7B%22normalized%22%3Atrue%7D%2C%22135e059f-30e6-491f-affe-873050e2a5aa%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D) and check that the layers appears in the same order, no like [this](https://team.carto.com/u/saleiva/builder/8123f4ff-52eb-4b9e-81dc-5ecf69469f9f/embed?vector=true&state=%7B%22map%22%3A%7B%22ne%22%3A%5B40.49918094806632%2C-74.06106948852539%5D%2C%22sw%22%3A%5B40.66709790906187%2C-73.89627456665039%5D%7D%2C%22widgets%22%3A%7B%2239ee0c57-74b9-433e-9daf-4d75605c97a9%22%3A%7B%22normalized%22%3Atrue%7D%2C%229bc213fd-c89b-43eb-bbb9-1e3a35c11d3b%22%3A%7B%22normalized%22%3Atrue%7D%2C%22135e059f-30e6-491f-affe-873050e2a5aa%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D).

Thank you! 👍

**Comment by jgoizueta** [comment]
The layer order seems just like in the raster LGTM :+1:

![screen shot 2017-02-14 at 11 39 29](https://cloud.githubusercontent.com/assets/5909/22925829/7040de40-f2aa-11e6-8e42-918ded4e55fa.png)
