### ISSUE TITLE
[Tangram R&D] Update API to make it compatible with 0.12.0 tangram release

### ISSUE THREAD

**Issue by donflopez** [CartoDB/tangram-carto#32]
The new tangram point outline feature has a different API.

It is:
```javascript
{ 
  outline: { 
     width: "5px",
     color: red
  }
}
```

We had:
```javascript
{ 
  outline_width: "5px",
  outline_color: red
}
```

**Comment by donflopez** [comment]
## Acceptance criteria

It should draw outlines.

### Steps:

- Go to the branch
- install all dependencies
- npm run start
- go to the browser
- click load and go to France
- check the markers with outlines

**Comment by dgaubert** [comment]
I'm afraid that I'm not seeing outlines:
![screen shot 2017-03-07 at 15 20 30](https://cloud.githubusercontent.com/assets/1936888/23660430/b693220e-0349-11e7-8ddb-b421d9805e7f.png)

**Comment by dgaubert** [comment]
Please, let me known when it's ready for acceptance

**Comment by dgaubert** [comment]
Is this what we wanna see?

![screen shot 2017-03-08 at 13 23 59](https://cloud.githubusercontent.com/assets/1936888/23703929/b52f2372-0402-11e7-8a63-863380e32e81.png)

**Comment by dgaubert** [comment]
Acceptance: OK
