### ISSUE TITLE
[Tangram R&D] Reduce the size of the library

### ISSUE THREAD

**Issue by donflopez** [CartoDB/tangram-carto#39]
The size of Tangram is pretty large, we have Ramda with 285kb and carto with 209kb, this is unacceptable.

To improve this, I've used ES6 decomposition for not loading the complete ramda library, now his size is 61kb, but for carto it is more complex, it is not ready to make loading decomposition so we are loading a lot of unused code, to avoid a huge part I've actively removed torque-reference from the bundle, so we have 81kb less leaving carto about 129kb.

![screen shot 2017-02-02 at 17 41 48](https://cloud.githubusercontent.com/assets/463462/25092668/01343ba8-238f-11e7-9eaf-e5ea209c35b8.png)
<img width="259" alt="screen shot 2017-04-17 at 16 59 16" src="https://cloud.githubusercontent.com/assets/463462/25092726/3f1e6722-238f-11e7-96b1-df4f49eccbeb.png">

**Comment by donflopez** [comment]
I also updated some of the dependencies

**Comment by donflopez** [comment]
@alonsogarciapablo can you take a look please?

**Comment by rafatower** [comment]
@donflopez what should be the acceptance procedure/criteria? thanks!

**Comment by donflopez** [comment]
I've put them on the PR @rafatower :)

**Comment by rafatower** [comment]
My understanding is that this issue is not deployed yet, right? just double-checking, thanks!

**Comment by donflopez** [comment]
It is deployed! I forgot to move this card @rafatower, sorry :)
