### ISSUE TITLE
Broken scene/map when blend mode != overlay

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/tangram-carto#48]
According to the [Tangram doc](https://mapzen.com/documentation/tangram/draw/#order) the `order` field is required in the "draw" field unless the `blend_mode` equals to `overlay` causing the markers to be invisible.

## Acceptance criteria

Before this PR, [some vector rendered maps](https://ramirocartodb.carto.com/builder/1d2baa22-1646-11e7-a6d8-0e3a376473ab/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B42.25393426299183%2C-71.61506652832033%5D%2C%22sw%22%3A%5B42.431565872579185%2C-70.68672180175783%5D%2C%22center%22%3A%5B42.34281279954019%2C-71.15089416503908%5D%2C%22zoom%22%3A11%7D%2C%22widgets%22%3A%7B%2220d0059f-31b6-498b-8e78-597a7a5db0cc%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D) were showing the following warning:

> tracker.js:15 Tangram v0.12.1 [warn]: Layer '6f8d5dc61e29648d71c4bdaa13a297dd', draw group 'points_7d2fe1c68205ae29b2d8f593359cd37f': 'order' parameter is required unless blend mode is 'overlay'

### Checks
- [x] The warning message is gone.

**Comment by alonsogarciapablo** [comment]
The following cartocss causes the JS error to show up in the console:

```
#layer {
  marker-width: ramp([avg_rely], range(32,2), quantiles(5));
  marker-fill: ramp([avg_rely], (#5c53a5, #b95e9a, #eb7f86, #fab27f, #f3e79b), quantiles);
  marker-fill-opacity: 1;
  marker-allow-overlap: true;
  marker-line-width: 0;
  marker-line-color: #FFF;
  marker-line-opacity: 1;
  marker-comp-op: multiply;
}
```

I will ensure that the error doesn't show up with the new code.
