### ISSUE TITLE
add a more complete example in the readme

### ISSUE THREAD

**Issue by javisantana** [CartoDB/tangram-carto#6]
I'd expect to have a full example of how to load tangram and use cartocss, like

```js

var cartocss = `
#layer {
   marker-fill: red;
   marker-width: 10;
}
`
scene_layer = Tangram.leafletLayer({
  scene: 'demos/scene.yaml',
  logLevel: 'debug'
}).addTo(map);

map.setView( [ 40.7, -74.009 ], 14 );
scene_layer.scene.config.layers.buildings.draw = CCSS.carto2Draw(cartocss);
scene_layer.scene.updateConfig();
});

```

Some other stuff:
- I'd also keep only one image (that it's related to the example)
- I'd publish the example live (using gh-pages) and add a link to it
- move the contributing section to a CONTRIBUTING file

**Comment by donflopez** [comment]
I've added the gh-pages branch with the demo working example
